# CQCommandExecutor

# 执行 PocketMine 指令的指令(CQ)
execute-command: "执行指令"

# 过滤返回消息中的 Escape 及颜色代码符号
filter-escapes: true

# Alias
# 插件将注册下列 CQ 指令，收到指令后执行对应 PocketMine 指令。
# Permission 表示权限，设置为 false 即表示仅管理员可用，否则所有人可用。
# 实际使用中请删除默认的测试指令
alias:
  在线列表:
    command: list
  踢出:
    command: kick
    permission: false